---
title: "map_fig"
author: "Alex Baecher & Ed Basham"
date: "2/2/2021"
output: html_document
---
# Load libraries
```{r Load libraries}
devtools::source_url("https://raw.githubusercontent.com/slamander/load_packages/main/prepare_libraries.R", sha1 = "609d531a319fcd855804de6bdcfe737cd6515332")

packages <- c("tidyverse",
              "ggthemes",
              "RColorBrewer",
              "scales",
              "raster",
              "rgeos",
              "unikn",
              "ggnewscale",
              "sf",
              "viridis",
              "wesanderson",
              "smoothr",
              "rnaturalearth",
              "rnaturalearthdata")

prepare_libraries(packages)
```

# Get global shapefile and DEM
```{r Get global shapefile and DEM}
islands <- 8000

ne_sf <- ne_countries(scale = "medium", returnclass = "sf") %>%
  subset(!sov_a3 == "ATA") %>%
  drop_crumbs(units::set_units(islands, km^2))

ne_sp <- ne_countries(scale = "medium", returnclass = "sp") %>%
  subset(!sov_a3 == "ATA") %>%
  drop_crumbs(units::set_units(islands, km^2)); plot(ne_sp)

proj4string <- crs(ne_sp)

gdem <- raster("data/demera5.tif") %>%
  raster::crop(ne_sp) %>%
  raster::mask(ne_sp) 

```

# Read in data
```{r Read in data}
dat <- read_csv("data/stripped_data/final/data_joined.csv") %>%
  dplyr::filter(taxa != "All mammals") %>%
  dplyr::filter(taxa != "Primates") %>%
  dplyr::mutate(taxa = as.factor(taxa),
                taxa_order = factor(taxa, levels = c("Bats","Birds","Small mammals","Amphibians")),
                elevation = as.numeric(elevation),
                scaled_met = as.numeric(rescale(corrected_biodiversity_metric_value, to = c(1e-05, 0.99999))),
                link = as.factor(link), 
                method = as.factor(method), 
                treatment = as.factor(treatment),
                continent = as.factor(continent),
                biodiversity_metric = as.factor(biodiversity_metric), 
                season = as.factor(season), 
                forest_type_iucn = as.factor(recode(forest_type_iucn_new, "dry forest" = "dry_forest")),
                mean_strata_height_p = as.numeric(scale(mean_strata_height_p)),
                canopy_height = as.numeric(scale(canopy_height)),
                latitude = as.numeric(latitude),
                longitude = as.numeric(longitude),
                strata = as.numeric(scale(mean_strata_height_p))) %>%
  dplyr::select(link, method, taxa_order, continent, biodiversity_metric, season, forest_type_iucn, 
                elevation, canopy_height, latitude, longitude, scaled_met, strata, year) %>%
  dplyr::mutate(forest_type_iucn = recode(forest_type_iucn, "dry forest" = "dry_forest"))

dat_link <- dat %>%
  dplyr::group_by(link, taxa_order, continent, year) %>%
  dplyr::summarize(elevation = as.numeric(mean(elevation)),
            latitude = as.numeric(mean(latitude)),
            longitude = as.numeric(mean(longitude)),
            canopy_height = as.numeric(mean(canopy_height)),
            year = mean(year)) %>%
  dplyr::mutate(decade = (year %/% 10)*10)
```

# Create base plot
```{r Create base plot}
{ggplot() + 
    geom_raster(data = as.data.frame(gdem, xy = T), aes(x = x, y = y, fill = demera5)) + 
    scale_fill_gradientn("Elevation (m)", colors = rev(wes_palette(name = "Royal2", n = 100, type = "continuous")), na.value = "#CCEEF9") + 
    geom_sf(data = ne_sf, col = "grey20", fill = NA, size = 0.2) +
    geom_hline(yintercept = c(-30,30), col = "grey60", linetype = "longdash") +
    new_scale_fill() +
    geom_point(data = dat_link, aes(x = longitude, y = latitude, fill = taxa_order), size = 2, shape = 21, stroke = 0.5, col = "white") +
    scale_fill_manual("Taxa", values = viridis(4, option = "viridis")) +
    theme_map() + theme(legend.position = c(0.5,0),
                        legend.direction = "horizontal",
                        legend.background = element_rect(fill="#CCEEF9"),
                        legend.key=element_blank(),
                        plot.background = element_rect(fill="#CCEEF9"));
ggsave("analysis/figures/study descriptions/rmap_royal2_rev_#CCEEF9_point.jpeg", width = 15, height = 6.07, units = "in", dpi = 600)}



{ggplot() + 
    geom_raster(data = as.data.frame(gdem, xy = T), aes(x = x, y = y, fill = demera5)) + 
    scale_fill_gradientn("Elevation (m)", colors = rev(grey.colors(256)), na.value = "white") + 
    geom_sf(data = ne_sf, col = "grey20", fill = NA, size = 0.2) +
    geom_hline(yintercept = c(-30,30), col = "grey60", linetype = "longdash") +
    new_scale_fill() +
    geom_point(data = dat_link, aes(x = longitude, y = latitude, fill = taxa_order), size = 2, shape = 21, stroke = 0.5, col = "grey20") +
    scale_fill_manual("Taxa", values = viridis(4, option = "viridis")) +
    theme_map() + theme(legend.position = c(0.5,0),
                        legend.direction = "horizontal",
                        legend.key=element_blank());
ggsave("analysis/figures/study descriptions/rmap_royal2_rev_grey_point.jpeg", width = 15, height = 6.07, units = "in", dpi = 600)}

```

```{r}
central_america <- st_crop(ne_sf, ymin = 5, ymax = 15, xmin = -88, xmax = -75) %>%
  as("Spatial")

ca_dem <- gdem %>%
  raster::crop(central_america) %>%
  raster::mask(central_america)

coords <- dat_link %>%
  ungroup() %>%
  dplyr::select(latitude, longitude)

coordinates(coords) <- ~ longitude + latitude
crs(coords) <- proj4string

coords_ca <- coords[central_america]@coords %>%
  as.data.frame()

panama <- ne_sf %>%
  filter(name == "Panama") %>%
  as("Spatial")

coordinates(coords_ca) <- ~ longitude + latitude
crs(coords_ca) <- proj4string

coords_pan <- coords_ca[panama]@coords %>%
  as.data.frame()

dat_link_ca <- dat_link[row.names(coords_ca)[5:14],]

dat_link_pan <- dat_link[row.names(coords_pan),] %>%
  mutate(longitude_j = longitude + runif(1,-1,3),
         latitude_j = latitude + runif(1,-1,3))

dat_link_pan_jittered <- dat_link_pan %>%
  rename(longitude_o = longitude, 
         latitude_o = latitude) %>%
  pivot_longer(c(longitude_o, longitude_j, latitude_o, latitude_j), names_to = c(".value","Category"), names_sep = "_") 

{ggplot() + 
    # geom_raster(data = as.data.frame(ca_dem, xy = T), aes(x = x, y = y, fill = demera5)) + 
    # scale_fill_gradientn("Elevation (m)", colors = rev(grey.colors(256)), na.value = "white") + 
    geom_sf(data = st_as_sf(central_america), col = "grey20", fill = "grey80", size = 0.5) +
    new_scale_fill() +
    geom_point(data = dat_link_ca, aes(x = longitude, y = latitude, fill = taxa_order), size = 5, shape = 21, stroke = 0.5, col = "grey20") +
    geom_point(data = dat_link_pan, aes(x = longitude_j, y = latitude_j, fill = taxa_order), size = 5, shape = 21, stroke = 0.5, col = "grey20") +
    geom_path(data = dat_link_pan_jittered, aes(x = longitude, y = latitude, group = link)) + 
    scale_fill_manual("Taxa", values = viridis(4, option = "viridis")) +
    annotate("rect", ymin = 5, ymax = 15, xmin = -88, xmax = -75, fill=NA, color = "black", size = 0.5) +
    theme_map() + theme(legend.position = "none",
                        legend.direction = "horizontal",
                        legend.key=element_blank());
ggsave("analysis/figures/study descriptions/rmap_royal2_rev_grey_point_inset.jpeg", width = 5, height = 4, units = "in", dpi = 600)
    }

```

# Create inset plots
```{r Create inset plots}
dat_link_study <- dat %>%
  dplyr::group_by(link, biodiversity_metric, taxa_order, continent, year, method) %>%
  dplyr::summarize(elevation = as.numeric(mean(elevation)),
            latitude = as.numeric(mean(latitude)),
            longitude = as.numeric(mean(longitude)),
            canopy_height = as.numeric(mean(canopy_height)),
            year = mean(year)) %>%
  dplyr::mutate(decade = (year %/% 10)*10)

{ggplot(dat_link_study) + 
  geom_boxplot(aes(x = taxa_order, y = elevation, fill = taxa_order), size = 1) + 
  ylab("Elevation (m)") + xlab("Taxa") +
  scale_fill_viridis_d() +
  theme_classic() +
  theme(legend.position = "none",
        panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size=1),
        axis.title.x = element_text(face = "bold", vjust = -0.5, size = rel(1.5)),
        axis.title.y = element_text(face = "bold", vjust = 2.5, size = rel(1.5)),
        plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm")) 
ggsave("analysis/figures/study descriptions/elevation_taxa.jpeg", width = 4.5, height = 4, units = "in", dpi = 300)}

{ggplot(dat_link_study) + 
  geom_bar(aes(x = factor(decade), fill = taxa_order), size = 1) + 
  ylab("# of study units") + xlab("Decade") + ylim(0,50) +
  scale_fill_viridis_d() +
  theme_classic() +
  theme(legend.position = "none",
        panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size=1),
        axis.title.x = element_text(face = "bold", vjust = -0.5, size = rel(1.5)),
        axis.title.y = element_text(face = "bold", vjust = 2.5, size = rel(1.5)),
        plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm")) 
ggsave("analysis/figures/study descriptions/decade_taxa.jpeg", width = 5, height = 3, units = "in", dpi = 300)}

{ggplot(dat_link_study) + 
  geom_bar(aes(x = biodiversity_metric, fill = taxa_order), size = 1) + 
  ylab("# of study units") + xlab("Biodiversity metric") +
  scale_fill_viridis_d() +
  theme_classic() +
  theme(legend.position = "none",
        panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size=1),
        axis.title.x = element_text(face = "bold", vjust = -0.5, size = rel(1.5)),
        axis.title.y = element_text(face = "bold", vjust = 2.5, size = rel(1.5)),
        plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm")) 
ggsave("analysis/figures/study descriptions/metric_taxa.jpeg", width = 3, height = 3, units = "in", dpi = 300)}

{ggplot(dat_link_study) + 
  geom_bar(aes(x = biodiversity_metric, fill = taxa_order), size = 1) + 
  ylab("# of study units") + xlab("Biodiversity metric") +
  scale_fill_viridis_d("Taxa") +
  theme_classic() +
  theme(panel.border = element_rect(linetype = "solid", colour = "black", fill = NA, size=1),
        axis.title.x = element_text(face = "bold", vjust = -0.5, size = rel(1.5)),
        axis.title.y = element_text(face = "bold", vjust = 2.5, size = rel(1.5)),
        plot.margin=unit(c(0.5,0.5,0.5,0.5),"cm")) 
ggsave("analysis/figures/study descriptions/metric_taxa_legend.jpeg", width = 4, height = 3, units = "in", dpi = 300)}

```

